/* ============================================================
   Rivera — map data (loaded before app.js on map.html only).
   The single source of truth for every map marker. To add a pin,
   append one object below (same "copy a block" ergonomic as a card
   in projects.html). A syntax slip here breaks ONLY the map, never
   the rest of the site. app.js reads `window.MAP_LOCATIONS`.
   ============================================================ */
/* ----------------------------------------------------------
   MAP_LOCATIONS — the single source of truth for every marker.
   Add a pin = append one object (the same "copy a block"
   ergonomic as a card in projects.html).
     id        unique string
     cat       'project'|'university'|'shopping'|'transit'|'landmark'
     nameEn/nameVi   label
     lat, lng        real coordinates
     address         street address / suburb (a proper noun, not translated)
     descEn/descVi   one calm line of description
     status          OPTIONAL {en,vi} — availability, shown for projects
     url             OPTIONAL — only projects carry a listing link
---------------------------------------------------------- */
window.MAP_LOCATIONS=[
  // --- Projects (the brand-brown heroes) ---
  { id:'aura-melbourne-square', cat:'project', url:'aura-melbourne-square.html',
    nameEn:'AURA at Melbourne Square', nameVi:'AURA tại Melbourne Square',
    lat:-37.8268, lng:144.9645,
    address:'7 Hoff Boulevard, Southbank VIC 3006',
    descEn:'The 67-level gateway tower of Melbourne Square, wrapped around the 3,745 sqm Kennedy Park.',
    descVi:'Toà tháp cửa ngõ 67 tầng của Melbourne Square, ôm quanh công viên Kennedy rộng 3.745 m².',
    status:{ en:'Pre-construction · selling now', vi:'Chưa khởi công · đang mở bán' } },
  { id:'collins-wharf-aluna', cat:'project', url:'collins-wharf-aluna.html',
    nameEn:'Collins Wharf · Aluna', nameVi:'Collins Wharf · Aluna',
    lat:-37.8202, lng:144.9395,
    address:'989 Collins Street, Docklands VIC',
    descEn:'Waterfront apartments on Collins Wharf, between the Yarra and Victoria Harbour.',
    descVi:'Căn hộ ven sông trên Collins Wharf, giữa sông Yarra và cảng Victoria.',
    status:{ en:'Off the plan · 2029', vi:'Theo bản vẽ · 2029' } },
  { id:'collins-wharf-ancora', cat:'project', url:'collins-wharf-ancora.html',
    nameEn:'Collins Wharf · Ancora', nameVi:'Collins Wharf · Ancora',
    lat:-37.8222, lng:144.9443,
    address:'971 Collins Street, Docklands VIC',
    descEn:'Waterfront apartments by Lendlease where Collins Street meets Victoria Harbour.',
    descVi:'Căn hộ ven nước của Lendlease, nơi phố Collins gặp cảng Victoria Harbour.',
    status:{ en:'Off the plan · 2027', vi:'Theo bản vẽ · 2027' } },
  { id:'671-chapel-street', cat:'project', url:'671-chapel-street.html',
    nameEn:'671 Chapel Street', nameVi:'671 Chapel Street',
    lat:-37.8380, lng:144.9923,   // approximate (northern end of Chapel St, Como precinct)
    address:'671 Chapel Street, South Yarra VIC',
    descEn:'South Yarra residences by CASA, with open views to the Yarra River and the city skyline.',
    descVi:'Căn hộ South Yarra của CASA, tầm nhìn thoáng ra sông Yarra và đường chân trời thành phố.',
    status:{ en:'Off the plan · 2028', vi:'Theo bản vẽ · 2028' } },
  { id:'380-melbourne', cat:'project', url:'380-melbourne.html',
    nameEn:'380 Melbourne', nameVi:'380 Melbourne',
    lat:-37.8118, lng:144.9601,
    address:'380 Lonsdale Street, Melbourne VIC',
    descEn:'CBD residence steps from Melbourne Central, RMIT and Queen Victoria Market.',
    descVi:'Căn hộ trung tâm, vài bước tới Melbourne Central, RMIT và chợ Queen Victoria.',
    status:{ en:'Move-in ready', vi:'Sẵn sàng dọn vào' } },
  { id:'aspire', cat:'project', url:'aspire.html',
    nameEn:'Aspire Melbourne', nameVi:'Aspire Melbourne',
    lat:-37.8133, lng:144.9556,
    address:'301 King Street, Melbourne VIC',
    descEn:'Tower apartments at the quiet western edge of the grid.',
    descVi:'Căn hộ tầng cao ở rìa tây yên tĩnh của lưới phố.',
    status:{ en:'Move-in ready', vi:'Sẵn sàng dọn vào' } },
  { id:'piccolo-house', cat:'project', url:'piccolo-house.html',
    nameEn:'Piccolo House', nameVi:'Piccolo House',
    lat:-37.8042, lng:145.0268,   // approximate (Barry St, near Studley Park Rd, Kew)
    address:'18 Barry Street, Kew VIC',
    descEn:'Five low-rise garden pavilions by Woods Bagot in leafy Kew, with a resort-style wellness level.',
    descVi:'Năm toà pavilion thấp tầng do Woods Bagot thiết kế giữa Kew xanh mát, với một tầng wellness chuẩn resort.',
    status:{ en:'Off the plan · 2027', vi:'Theo bản vẽ · 2027' } },

  // --- Universities ---
  { id:'unimelb', cat:'university',
    nameEn:'University of Melbourne (Parkville)', nameVi:'Đại học Melbourne (Parkville)',
    lat:-37.7964, lng:144.9612,
    address:'Parkville, VIC',
    descEn:'Leading university, a short tram north in Parkville.',
    descVi:'Đại học hàng đầu, một chuyến tram ngắn lên phía bắc ở Parkville.' },
  { id:'rmit', cat:'university',
    nameEn:'RMIT University', nameVi:'Đại học RMIT',
    lat:-37.8076, lng:144.9632,
    address:'La Trobe Street, Melbourne VIC',
    descEn:'City campus along the north edge of the grid.',
    descVi:'Khuôn viên trung tâm dọc rìa bắc của lưới phố.' },
  { id:'monash-college-docklands', cat:'university',
    nameEn:'Monash College (Docklands)', nameVi:'Monash College (Docklands)',
    lat:-37.8204, lng:144.9450,
    address:'750 Collins Street, Docklands VIC',
    descEn:'Pathway college in Docklands, beside Collins Square.',
    descVi:'Trường dự bị tại Docklands, cạnh Collins Square.' },
  { id:'victoria-university', cat:'university',
    nameEn:'Victoria University (City)', nameVi:'Đại học Victoria (Thành phố)',
    lat:-37.8108, lng:144.9580,
    address:'370 Little Lonsdale Street, Melbourne VIC',
    descEn:'City campus tower on Little Lonsdale Street.',
    descVi:'Khuôn viên trung tâm trên phố Little Lonsdale.' },
  { id:'monash-clayton', cat:'university',
    nameEn:'Monash University (Clayton)', nameVi:'Đại học Monash (Clayton)',
    lat:-37.9106, lng:145.1347,
    address:'Wellington Road, Clayton VIC',
    descEn:'Australia’s largest university, in the south-east at Clayton.',
    descVi:'Đại học lớn nhất nước Úc, ở phía đông nam tại Clayton.' },

  // --- Shopping ---
  { id:'emporium', cat:'shopping',
    nameEn:'Emporium Melbourne', nameVi:'Emporium Melbourne',
    lat:-37.8123, lng:144.9645,
    address:'287 Lonsdale Street, Melbourne VIC',
    descEn:'Connected laneway shopping between Lonsdale and Bourke.',
    descVi:'Khu mua sắm nối liền trong hẻm giữa Lonsdale và Bourke.' },
  { id:'qv', cat:'shopping',
    nameEn:'QV Melbourne', nameVi:'QV Melbourne',
    lat:-37.8110, lng:144.9659,
    address:'Lonsdale & Swanston Street, Melbourne VIC',
    descEn:'Open-air precinct of shops and grocers off Swanston.',
    descVi:'Khu phố mở với cửa hàng và chợ thực phẩm cạnh Swanston.' },

  // --- Transit. The Metro Tunnel stations opened 30 Nov 2025; the new-station
  //     coordinates below are APPROXIMATE (street-level estimates, not surveyed). ---
  { id:'flinders-st', cat:'transit',
    nameEn:'Flinders Street Station', nameVi:'Ga Flinders Street',
    lat:-37.8183, lng:144.9671,
    address:'Flinders Street, Melbourne VIC',
    descEn:'The city’s main rail hub, on the river.',
    descVi:'Ga đường sắt chính của thành phố, bên dòng sông.' },
  { id:'southern-cross', cat:'transit',
    nameEn:'Southern Cross Station', nameVi:'Ga Southern Cross',
    lat:-37.8183, lng:144.9525,
    address:'Spencer Street, Melbourne VIC',
    descEn:'Regional trains and airport coaches on Spencer.',
    descVi:'Tàu liên vùng và xe sân bay trên phố Spencer.' },
  { id:'flagstaff', cat:'transit',
    nameEn:'Flagstaff Station', nameVi:'Ga Flagstaff',
    lat:-37.8113, lng:144.9558,   // approximate
    address:'William Street, Melbourne VIC',
    descEn:'City Loop station at the quiet north-west corner of the grid.',
    descVi:'Ga City Loop ở góc tây bắc yên tĩnh của lưới phố.' },
  { id:'parliament', cat:'transit',
    nameEn:'Parliament Station', nameVi:'Ga Parliament',
    lat:-37.8110, lng:144.9727,
    address:'Spring Street, Melbourne VIC',
    descEn:'City Loop station beneath Spring Street and the gardens.',
    descVi:'Ga City Loop bên dưới phố Spring và khu vườn.' },
  { id:'state-library-station', cat:'transit',
    nameEn:'State Library Station', nameVi:'Ga State Library',
    lat:-37.8094, lng:144.9645,   // approximate (Metro Tunnel, new)
    address:'Swanston Street, Melbourne VIC',
    descEn:'New Metro Tunnel station beneath the library precinct.',
    descVi:'Ga Metro Tunnel mới bên dưới khu thư viện.' },
  { id:'town-hall-station', cat:'transit',
    nameEn:'Town Hall Station', nameVi:'Ga Town Hall',
    lat:-37.8158, lng:144.9668,   // approximate (Metro Tunnel, new)
    address:'Swanston Street, Melbourne VIC',
    descEn:'New Metro Tunnel station by the Town Hall on Swanston.',
    descVi:'Ga Metro Tunnel mới cạnh Tòa thị chính trên phố Swanston.' },
  { id:'parkville-station', cat:'transit',
    nameEn:'Parkville Station', nameVi:'Ga Parkville',
    lat:-37.7983, lng:144.9583,   // approximate (Metro Tunnel, new)
    address:'Grattan Street, Parkville VIC',
    descEn:'New Metro Tunnel station at the university and hospitals.',
    descVi:'Ga Metro Tunnel mới tại khu đại học và bệnh viện.' },

  // --- Landmarks (iconic civic places + market/library; a normal toggleable category) ---
  { id:'town-hall', cat:'landmark',
    nameEn:'Melbourne Town Hall', nameVi:'Tòa thị chính Melbourne',
    lat:-37.8148, lng:144.9665,
    address:'Swanston & Collins Street, Melbourne VIC',
    descEn:'Civic landmark on the Swanston and Collins corner.',
    descVi:'Công trình biểu tượng ở góc Swanston và Collins.' },
  { id:'parliament-house', cat:'landmark',
    nameEn:'Parliament House', nameVi:'Tòa nhà Nghị viện',
    lat:-37.8113, lng:144.9730,
    address:'Spring Street, Melbourne VIC',
    descEn:'State parliament and gardens at the top of the grid.',
    descVi:'Nghị viện bang và vườn cây ở đỉnh lưới phố.' },
  { id:'state-library', cat:'landmark',
    nameEn:'State Library of Victoria', nameVi:'Thư viện Bang Victoria',
    lat:-37.8098, lng:144.9652,
    address:'328 Swanston Street, Melbourne VIC',
    descEn:'The city’s reading rooms and front lawn on Swanston.',
    descVi:'Phòng đọc và bãi cỏ phía trước của thành phố trên phố Swanston.' },
  { id:'fed-square', cat:'landmark',
    nameEn:'Federation Square', nameVi:'Quảng trường Federation',
    lat:-37.8180, lng:144.9691,
    address:'Swanston & Flinders Street, Melbourne VIC',
    descEn:'Riverside plaza for galleries and gatherings.',
    descVi:'Quảng trường bên sông cho phòng tranh và sự kiện.' },
  { id:'queen-vic-market', cat:'landmark',
    nameEn:'Queen Victoria Market', nameVi:'Chợ Queen Victoria',
    lat:-37.8076, lng:144.9568,
    address:'Queen Street, Melbourne VIC',
    descEn:'Heritage produce market just north-west of the grid.',
    descVi:'Khu chợ di sản bán nông sản, ngay phía tây bắc lưới phố.' },
  { id:'melbourne-central', cat:'landmark',
    nameEn:'Melbourne Central', nameVi:'Melbourne Central',
    lat:-37.8102, lng:144.9628,
    address:'211 La Trobe Street, Melbourne VIC',
    descEn:'Major retail and a Metro station under one roof.',
    descVi:'Trung tâm mua sắm lớn và một ga Metro dưới cùng một mái.' }
];
